// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/proto/v1/analyticsService.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NewTask) Reset() {
	*x = NewTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_analyticsService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTask) ProtoMessage() {}

func (x *NewTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_analyticsService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTask.ProtoReflect.Descriptor instead.
func (*NewTask) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_analyticsService_proto_rawDescGZIP(), []int{0}
}

func (x *NewTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UsersTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Login  string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *UsersTask) Reset() {
	*x = UsersTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_analyticsService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersTask) ProtoMessage() {}

func (x *UsersTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_analyticsService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersTask.ProtoReflect.Descriptor instead.
func (*UsersTask) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_analyticsService_proto_rawDescGZIP(), []int{1}
}

func (x *UsersTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UsersTask) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type TimeStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *UsersTask `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	TimeStart    string     `protobuf:"bytes,2,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	NewTaskState *string    `protobuf:"bytes,3,opt,name=newTaskState,proto3,oneof" json:"newTaskState,omitempty"`
}

func (x *TimeStart) Reset() {
	*x = TimeStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_analyticsService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStart) ProtoMessage() {}

func (x *TimeStart) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_analyticsService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStart.ProtoReflect.Descriptor instead.
func (*TimeStart) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_analyticsService_proto_rawDescGZIP(), []int{2}
}

func (x *TimeStart) GetUser() *UsersTask {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TimeStart) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *TimeStart) GetNewTaskState() string {
	if x != nil && x.NewTaskState != nil {
		return *x.NewTaskState
	}
	return ""
}

type TimeEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *UsersTask `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	TimeEnd      string     `protobuf:"bytes,2,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	NewTaskState *string    `protobuf:"bytes,3,opt,name=newTaskState,proto3,oneof" json:"newTaskState,omitempty"`
}

func (x *TimeEnd) Reset() {
	*x = TimeEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_v1_analyticsService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEnd) ProtoMessage() {}

func (x *TimeEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_analyticsService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEnd.ProtoReflect.Descriptor instead.
func (*TimeEnd) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_analyticsService_proto_rawDescGZIP(), []int{3}
}

func (x *TimeEnd) GetUser() *UsersTask {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TimeEnd) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

func (x *TimeEnd) GetNewTaskState() string {
	if x != nil && x.NewTaskState != nil {
		return *x.NewTaskState
	}
	return ""
}

var File_api_proto_v1_analyticsService_proto protoreflect.FileDescriptor

var file_api_proto_v1_analyticsService_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x19, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x39, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x94, 0x01, 0x0a, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72,
	0x65, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x27, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0c, 0x6e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x8e, 0x01, 0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x2f, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x27, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x54,
	0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x32, 0xd2, 0x01, 0x0a, 0x09, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x19,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x43, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3f, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x45, 0x6e, 0x64, 0x12, 0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x70, 0x6b, 0x67, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x65, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_v1_analyticsService_proto_rawDescOnce sync.Once
	file_api_proto_v1_analyticsService_proto_rawDescData = file_api_proto_v1_analyticsService_proto_rawDesc
)

func file_api_proto_v1_analyticsService_proto_rawDescGZIP() []byte {
	file_api_proto_v1_analyticsService_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_analyticsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_v1_analyticsService_proto_rawDescData)
	})
	return file_api_proto_v1_analyticsService_proto_rawDescData
}

var file_api_proto_v1_analyticsService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_analyticsService_proto_goTypes = []interface{}{
	(*NewTask)(nil),       // 0: commandsApi.NewTask
	(*UsersTask)(nil),     // 1: commandsApi.UsersTask
	(*TimeStart)(nil),     // 2: commandsApi.TimeStart
	(*TimeEnd)(nil),       // 3: commandsApi.TimeEnd
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_api_proto_v1_analyticsService_proto_depIdxs = []int32{
	1, // 0: commandsApi.TimeStart.user:type_name -> commandsApi.UsersTask
	1, // 1: commandsApi.TimeEnd.user:type_name -> commandsApi.UsersTask
	0, // 2: commandsApi.Analytics.CreateTask:input_type -> commandsApi.NewTask
	2, // 3: commandsApi.Analytics.SetTimeStart:input_type -> commandsApi.TimeStart
	3, // 4: commandsApi.Analytics.SetTimeEnd:input_type -> commandsApi.TimeEnd
	4, // 5: commandsApi.Analytics.CreateTask:output_type -> google.protobuf.Empty
	4, // 6: commandsApi.Analytics.SetTimeStart:output_type -> google.protobuf.Empty
	4, // 7: commandsApi.Analytics.SetTimeEnd:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_analyticsService_proto_init() }
func file_api_proto_v1_analyticsService_proto_init() {
	if File_api_proto_v1_analyticsService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_v1_analyticsService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_analyticsService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_analyticsService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_v1_analyticsService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_v1_analyticsService_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_proto_v1_analyticsService_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_v1_analyticsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_analyticsService_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_analyticsService_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_analyticsService_proto_msgTypes,
	}.Build()
	File_api_proto_v1_analyticsService_proto = out.File
	file_api_proto_v1_analyticsService_proto_rawDesc = nil
	file_api_proto_v1_analyticsService_proto_goTypes = nil
	file_api_proto_v1_analyticsService_proto_depIdxs = nil
}
