version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./docker-compose.d/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d