global:
  scrape_interval:     120s
  evaluation_interval: 120s

  external_labels:
    monitor: 'analytics-service'


rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: analytics-service
    scrape_interval: 10s
    static_configs:
      - targets:
          - localhost:9001